version: '3.8'

services:
  backend:
    build:
      context: ./
      dockerfile: ./docker/backend.dockerfile
    environment:
      NODE_ENV: ${NODE_ENV:-PROD}
      LOG_LEVEL: ${LOG_LEVEL:-info}
    ports:
      - 9090:9090
    restart: on-failure
  envoy:
    build:
      context: ./
      dockerfile: ./docker/envoy.dockerfile
    depends_on:
      - backend
    ports:
      - 8080:8080
    restart: on-failure